title X-Linux
version 1.0.0
linux /vmlinuz-linux-cachyos-rc
initrd /intel-ucode.img
initrd /amd-ucode.img
initrd /initramfs-linux-cachyos-rc.img
options root=/dev/nvme0n1p2 mitigations=off intel_iommu=off amd_iommu=off mce=off norandmaps nokaslr nowatchdog nohpet splash quiet rw
