# HighPassSharpen
HighPassSharpen = /opt/reshade/shaders/HighPassSharpen.fx
HighPassSharpen.HighPassSharpRadius = 3
HighPassSharpen.HighPassBlendMode = 2
HighPassSharpen.HighPassBlendIfLight = 125
HighPassSharpen.HighPassSharpStrength = 1
HighPassSharpen.HighPassDarkIntensity = 5
HighPassSharpen.HighPassLightIntensity = 2.5
HighPassSharpen@RESHADE_DEPTH_INPUT_IS_MIRRORED = 0

# LevelsPlus
LevelsPlus = /opt/reshade/shaders/LevelsPlus.fx
LevelsPlus.InputBlackPoint[0] = 0.05
LevelsPlus.InputBlackPoint[1] = 0.05
LevelsPlus.InputBlackPoint[2] = 0.05
LevelsPlus.InputWhitePoint[0] = 0.95
LevelsPlus.InputWhitePoint[1] = 0.95
LevelsPlus.InputWhitePoint[2] = 0.95
LevelsPlus@RESHADE_DEPTH_INPUT_IS_MIRRORED = 0

effects = LevelsPlus:HighPassSharpen
