LevelsPlus=/opt/reshade/shaders/LevelsPlus.fx
LevelsPlus@RESHADE_DEPTH_INPUT_IS_MIRRORED=0
LevelsPlus.InputBlackPoint[0]=0.05
LevelsPlus.InputBlackPoint[1]=0.05
LevelsPlus.InputBlackPoint[2]=0.05
LevelsPlus.InputWhitePoint[0]=0.95
LevelsPlus.InputWhitePoint[1]=0.95
LevelsPlus.InputWhitePoint[2]=0.95
Colourfulness=/opt/reshade/shaders/Colourfulness.fx
Colourfulness@RESHADE_DEPTH_INPUT_IS_MIRRORED=0
Colourfulness@temporal_dither=1
Colourfulness@fast_luma=0
Colourfulness.enable_dither=true
Colourfulness.colourfulness=-0.1
Colourfulness.lim_luma=1
MagicBloom=/opt/reshade/shaders/MagicBloom.fx
MagicBloom@RESHADE_DEPTH_INPUT_IS_MIRRORED=0
MagicBloom@MAGICBLOOM_ADAPT_RESOLUTION=256
MagicBloom@MAGICBLOOM_BLUR_PRECALCULATED=1
MagicBloom@MAGICBLOOM_NOADAPT=0
MagicBloom@MAGICBLOOM_NODIRT=1
MagicBloom.fBloom_Threshold=10
MagicBloom.fBloom_Intensity=10
MagicBloom.iAdapt_Precision=0
MagicBloom.fAdapt_Speed=1
MagicBloom.fExposure=0.2
HighPassSharpen=/opt/reshade/shaders/HighPassSharpen.fx
HighPassSharpen@RESHADE_DEPTH_INPUT_IS_MIRRORED=0
HighPassSharpen.HighPassSharpRadius=3
HighPassSharpen.HighPassSharpStrength=1
HighPassSharpen.HighPassBlendMode=2
HighPassSharpen.HighPassBlendIfLight=125
HighPassSharpen.HighPassDarkIntensity=5
HighPassSharpen.HighPassLightIntensity=2.5
effects=LevelsPlus:Colourfulness:MagicBloom:HighPassSharpen
