title X-Arch
version 1.0.0
linux /vmlinuz-linux-cachyos-rc
initrd /intel-ucode.img
initrd /initramfs-linux-cachyos-rc.img
options root=/dev/nvme0n1p2 mitigations=off iommu=off intel_pstate=passive norandmaps nokaslr nomce nowatchdog nohpet splash quiet rw
