[Resolve]
	ReadEtcHosts=true
	CacheFromLocalhost=true
	Cache=true
	MulticastDNS=true
	LLMNR=true
	ResolveUnicastSingleLabel=true
	DNSOverTLS=false
	DNS=76.76.2.11#no-malware-ads-typo.freedns.controld.com
	FallbackDNS=2606:1a40::11#no-malware-ads-typo.freedns.controld.com
	Domains=~.
