#!/usr/bin/env dash
if [ $(basename $0) != wine ]; then
	wine-staging $(basename $0) "$@"
	exit
fi
export LSFG_PROCESS=wine
export LSFGVK_PROFILE=wine
export VK_INSTANCE_LAYERS=VK_LAYER_MESA_device_select:VK_LAYER_MESA_anti_lag:VK_LAYER_LSFGVK_frame_generation:VK_LAYER_VKBASALT_OVERLAY_post_processing:VK_LAYER_MANGOHUD_overlay
switcherooctl launch --gpu 0 gamemoderun wine-staging start /realtime /b "$@"
exit
